server:
  port: 8000

spring:
  application:
    name: stream-provider
  cloud:
    stream:
      binders:
        default_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: guest
                password: guest
      bindings:
        pay:
          destination: pay.exchange
          content-type: application/json
          binder: default_rabbit
        order:
          destination: order.exchange
          content-type: application/json
          binder: default_rabbit