server:
  port: 8001

spring:
  application:
    name: stream-provider
  cloud:
    stream:
      binders:
        default_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: admin
                password: admin
      bindings:
        pay:
          destination: pay.exchange
          content-type: application/json
          binder: default_rabbit
          group: group
        order:
          destination: order.exchange
          content-type: application/json
          binder: default_rabbit
          group: group