server:
  port: 8081

spring:
  application:
    name: eureka-hystrix-provider

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: eureka-hystrix-provider-8080
    prefer-ip-address: true